       IDENTIFICATION DIVISION.
       PROGRAM-ID. DWZ.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  A     PIC A(20) VALUE 9.
       
       PROCEDURE DIVISION.
       DISPLAY A.
       STOP RUN.
