       IDENTIFICATION DIVISION.
       PROGRAM-ID. DWZ.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  A     PIC 9(4) VALUE 1747.
       
       PROCEDURE DIVISION.
       DISPLAY A.
       STOP RUN.
